name: Unzip and Push

on:
  workflow_dispatch:

jobs:
  unzip-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip the uploaded file
        run: |
          unzip -o threejs-online-thirdperson-final.zip -d extracted

      - name: Move extracted files to root
        run: |
          shopt -s dotglob
          mv extracted/* ./
          rm -rf extracted

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Unzipped and pushed the contents of the zip file"
          git push
