name: Full Cleanup

on:
  workflow_dispatch:

jobs:
  delete-all:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Remove all files and folders except .github
      run: |
        shopt -s extglob
        rm -rf !(README.md|.git|.github)

    - name: Add Clean README
      run: echo "# Clean Repo" > README.md

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Cleanup repo: remove all except .github"
        git push
