name: Unzip and Commit

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip file
        run: unzip threejs-online-thirdperson-final.zip -d temp

      - name: Move contents
        run: |
          mv temp/* . || true
          rm -rf temp threejs-online-thirdperson-final.zip

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Unzipped and pushed contents" || echo "Nothing to commit"
          git push
