name: Clean All Files Except .github

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Remove all files and folders except .github
      run: |
        shopt -s extglob
        rm -rf !(README.md|.git|.github)

    - name: Add clean README
      run: echo "# Clean Repository" > README.md

    - name: Commit and Push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Cleanup: remove all files except .github"
        git push
